import { jsPDF } from 'jspdf';
import { BudgetData, ArchetypeId } from '@/types';

export const generatePDF = (data: BudgetData, archetype: any) => {
  try {
    const doc = new jsPDF();
    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;
    let yPosition = 20;
    const margin = 20;
    const lineHeight = 7;

    // Title
    doc.setFontSize(24);
    doc.setTextColor(0, 102, 204); // Primary color
    doc.text('MarketMap Report', margin, yPosition);
    yPosition += 15;

    // Subtitle
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Your ${archetype.name} Marketing Platform Map`, margin, yPosition);
    yPosition += 15;

    // Budget section
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Budget: $' + data.budget.toLocaleString(), margin, yPosition);
    yPosition += 10;

    // Hero Channel
    doc.setFontSize(12);
    doc.setTextColor(0, 102, 204);
    doc.text('🎯 HERO CHANNEL', margin, yPosition);
    yPosition += 8;

    if (data.hero_channel) {
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.text(data.hero_channel.platform, margin + 5, yPosition);
      yPosition += 5;
      doc.text(`CAC: ${data.hero_channel.typical_cac}`, margin + 5, yPosition);
      yPosition += 5;
      doc.text(`Budget: $${data.budget_breakdown.hero.toLocaleString()} (50%)`, margin + 5, yPosition);
      yPosition += 10;
    }

    // Support Channels
    doc.setFontSize(12);
    doc.setTextColor(0, 102, 204);
    doc.text('📊 SUPPORT CHANNELS (30%)', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    data.support_channels.slice(0, 2).forEach((channel) => {
      doc.text(`• ${channel.platform} - CAC: ${channel.typical_cac}`, margin + 5, yPosition);
      yPosition += 5;
    });
    yPosition += 5;

    // Hidden Goldmines
    doc.setFontSize(12);
    doc.setTextColor(0, 102, 204);
    doc.text('💎 HIDDEN GOLDMINES (20%)', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    data.hidden_goldmines.slice(0, 3).forEach((goldmine) => {
      doc.text(`• ${goldmine.platform}`, margin + 5, yPosition);
      yPosition += 5;
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
      }
    });

    // Budget Breakdown
    yPosition += 5;
    doc.setFontSize(12);
    doc.setTextColor(0, 102, 204);
    doc.text('Budget Breakdown', margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Hero Channel (50%): $${data.budget_breakdown.hero.toLocaleString()}`, margin + 5, yPosition);
    yPosition += 5;
    doc.text(`Support Channels (30%): $${data.budget_breakdown.support.toLocaleString()}`, margin + 5, yPosition);
    yPosition += 5;
    doc.text(`Experiments (20%): $${data.budget_breakdown.experiments.toLocaleString()}`, margin + 5, yPosition);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by MarketMap • marketmap.cloud', margin, pageHeight - 10);

    return doc;
  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  }
};

export const downloadPDF = (doc: jsPDF, category: ArchetypeId) => {
  const filename = `marketmap_report_${category}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};
